name: Build & Test

on: [ push, pull_request, workflow_call, workflow_dispatch ]

jobs:
  check_linux:
    name: Performing Linux Build / Update
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt

      - name: Running Tests
        run: cargo check --all-features

      - name: Checking Formatting
        run: cargo fmt --all -- --check

      - name: Performing Clippy Test
        run: cargo clippy --all-targets --all-features -- -D warnings